// Code generated by encore. DO NOT EDIT.

package llm

import (
	"context"
	types "encore.app/llm/types"
)

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

func GenerateResponse(ctx context.Context, p *GenerateRequest) (*Action, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*Action)(nil), nil
}

// GetGenerationStatus retrieves the status of a generation request
func GetGenerationStatus(ctx context.Context, id string) (*Action, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*Action)(nil), nil
}

// ProcessRequest publishes an LLM request to the generation topic
func ProcessRequest(ctx context.Context, p *types.LLMRequestEvent) error {
	// The implementation is elided here, and generated at compile-time by Encore.
	return nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	GenerateResponse(ctx context.Context, p *GenerateRequest) (*Action, error)

	// GetGenerationStatus retrieves the status of a generation request
	GetGenerationStatus(ctx context.Context, id string) (*Action, error)

	// ProcessRequest publishes an LLM request to the generation topic
	ProcessRequest(ctx context.Context, p *types.LLMRequestEvent) error
}
